BlogWeek/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.PostListView.as_view(), name='home'),
    path('post/<pk>', views.PostDetailViews.as_view(), name='post'),
    path('author/<pk>', views.AuthorListView.as_view(), name='author'),
    path('category/<pk>', views.CategoryListView.as_view(), name='category'),
    path('date/<int:month_id>/<int:year_id>/', views.DateListView.as_view(), name='date'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('update/<pk>', views.PostUpdateview.as_view(), name='update'),
    path('delete/<pk>', views.PostDeleteView.as_view(), name='delete'),
    path('abouts/', views.AboutTemplateView.as_view(),name='abouts'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/',views.RegisterUser.as_view(), name='register'),
    path('profile/<pk>', views.ProfileDetailView.as_view(), name='profile')
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200, verbose_name='nombre', unique=True)
    active = models.BooleanField(default=True, verbose_name='activo')
    created = models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')
    updated = models.DateField(auto_now_add=True, null=True, blank=True, verbose_name='Fecha de actualizacion')

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['name']

    def __str__(self):
        return self.name
    
class Tag(models.Model):
    name = models.CharField(max_length=200, verbose_name='Nombre', unique=True)
    active = models.BooleanField(default=True, verbose_name='Activo')
    created = models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')
    updated = models.DateField(auto_now_add=True, null=True, blank=True, verbose_name='Fecha de actualizacion')

    class Meta:
        verbose_name = 'Etiqueta'
        verbose_name_plural = 'Etiquetas'
        ordering = ['name']

    def __str__(self):
        return self.name
    
class Post(models.Model):
    title = models.CharField(max_length=250, verbose_name='Titulo')
    excerpt = models.TextField(verbose_name='Bajada')
    # ckeditor
    content = RichTextField(verbose_name='Contenido')
    image = models.ImageField(upload_to='post', verbose_name='Imagen', null=True, blank=True)
    published = models.BooleanField(default=False, verbose_name='Publicado')
    created = models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')
    updated = models.DateField(auto_now_add=True, null=True, blank=True, verbose_name='Fecha de actualizacion')

    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='get_posts', verbose_name='Categoria')
    tag = models.ManyToManyField(Tag, verbose_name='Etiqueta')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='get_posts', verbose_name='Autor')

    class Meta:
        verbose_name = 'Publicacion'
        verbose_name_plural = 'Publicaciones'
        ordering = ['-created']
    
    def __str__(self):
        return self.title
    
class About(models.Model):
    description = models.CharField(max_length=250, verbose_name='Descripcion')
    created = models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')
    updated = models.DateField(auto_now_add=True, null=True, blank=True, verbose_name='Fecha de actualizacion')

    class Meta:
        verbose_name = 'Acerca de'
        verbose_name_plural = 'Acerca de nosotros'
        ordering = ['created',]
    
    def __str__(self):
        return self.description
    
class Link(models.Model):
    key = models.CharField(max_length=100, verbose_name='key Link')
    name = models.CharField(max_length=100, verbose_name='Red Social')
    url = models.URLField(max_length=350, blank=True, null=True, verbose_name='Enlace')
    icon = models.CharField(max_length=100, verbose_name='Icono')
    created = models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')
    updated = models.DateField(auto_now_add=True, null=True, blank=True, verbose_name='Fecha de actualizacion')

    class Meta:
        verbose_name = 'Red Social'
        verbose_name_plural = 'Redes Sociales'
        ordering = ['name',]
    def __str__(self):
        return self.name

core/forms.py
from django import forms
from .models import Post
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'excerpt', 'content', 'image', 'category', 'tag']
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control'}),
            'excerpt': forms.Textarea(attrs={'class':'form-control'}),
            'content': forms.Textarea(attrs={'class':'form-control'}),
            'image': forms.ClearableFileInput(attrs={'class':'form-control'}),
            'category': forms.Select(attrs={'class':'form-control'}),
            'tag': forms.SelectMultiple(attrs={'class':'form-control'}),
        }

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
        ]
        labels = {
            'username':'Usuario',
            'first_name':'Primer nombre',
            'last_name':'Apellido',
            'email':'Correo',
        }
        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control'}),
            'first_name': forms.TextInput(attrs={'class':'form-control'}),
            'last_name': forms.TextInput(attrs={'class':'form-control'}),
            'email': forms.TextInput(attrs={'class':'form-control'}),
        }

core/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from .forms import PostForm, RegisterForm
from .models import Post, Category
from django.contrib.auth.models import User
import datetime
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView, TemplateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

class PostListView(ListView):
    model = Post
    paginate_by = 3
    template_name = 'core/home.html'
    queryset = Post.objects.filter(published=True)
    
class PostDetailViews(DetailView):
   model = Post
   template_name = 'core/detail.html'

class CategoryListView(ListView):
    model = Category
    template_name = 'core/category.html'
   
    def get_queryset(self):
        category_id = self.kwargs['pk']
        if category_id:
            return Post.objects.filter(category=category_id, published=True)
        return super().get_queryset()
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.get(id=self.kwargs['pk'])
        return context
    
class AuthorListView(ListView):
    model = User
    template_name = 'core/author.html'

    def get_queryset(self):
        author_id = self.kwargs['pk']
        if author_id:
            return Post.objects.filter(author=author_id, published=True)
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = User.objects.get(id=self.kwargs['pk'])
        return context
    
class DateListView(ListView):
    model = Post
    template_name = 'core/date.html'

    def get_queryset(self):
        return super(ProvinciaList,
        self).get_queryset().filter(comunidad_id=self.kwargs.get("comunidad_id"))
    def get_queryset(self):
        month_id = self.kwargs['month_id']
        year_id = self.kwargs['year_id']
        #month_id = self.request.GET['month']
        #year_id = self.request.GET['year']
        
        return Post.objects.filter(published=True, created__month=month_id, created__year=year_id)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['date'] = datetime.date(self.kwargs['year_id'],self.kwargs['month_id'], 1)
        return context 

class AboutTemplateView(TemplateView):
    template_name = 'core/abouts.html'

@method_decorator(login_required, name='dispatch')
class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    success_url = reverse_lazy('home')

@method_decorator(login_required, name='dispatch')
class PostUpdateview(UpdateView):
    model = Post
    form_class = PostForm
    template_name_suffix = '_update_form'
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('update', args=[self.object.id]) + '?ok'

@method_decorator(login_required, name='dispatch')
class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('home')

class RegisterUser(CreateView):
    model = User
    template_name = 'registration/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('home')

@method_decorator(login_required, name='dispatch')
class ProfileDetailView(DetailView):
    model = User
    form_class = RegisterForm
    template_name = 'registration/profile.html'

core/templates/core/abouts.html
{% extends 'core/base.html' %}
{% block content %}
<div class="p-4 mb-3 bg-light rounded">
    <h4 class="fst-italic">Acerca nuestro</h4>
    <p>{{ abouts }}</p>
  </div>
{% endblock %}

core/templates/core/author.html
{% extends 'core/base.html' %}
{% block content %}
  {% if post_list %}
    <div class="alert alert-success" role="alert">
        Estos son todos los post del autor <strong>{{ author.first_name }}, {{ author.last_name }}</strong>
    </div>
    {% for post in post_list %}  
    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-300 position-relative">
      <div class="object-fit-cover col-auto d-none d-lg-block">
        <img src={{ post.image.url }} width="300" height="250"  class="img-fluid rounded-start " alt="...">          
      </div>
      
      <div class="col-6 p-2 d-flex flex-column position-static">
        <strong class="d-inline-block mb-1 mt-0 text-primary">{{ post.category }}</strong>
        <h3 class="mb-0">{{ post.title|truncatewords:'7' }}</h3>
        <div class="mb-1 text-muted">{{ post.created | date:'d b y'}}</div>
        <p class="card-text mb-auto">{{ post.excerpt|truncatewords:'30' }}</p>
        <a href={% url 'post' post.id %} class="stretched-link">Seguir leyendo</a>
      </div>
    </div>
    {% endfor %}  
  {% else %}
    <div class="alert alert-danger" role="alert">
      <strong>{{ author.first_name }}, {{ author.last_name }}</strong>
       no tiene post publicados
    </div>
  {% endif %}
{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog Semanal</title>
    {% load static %}
    <link href={% static 'core/css/bootstrap.min.css' %} rel="stylesheet">
    <link href={% static 'core/css/blog.css' %} rel="stylesheet">
    <!--bootstrap-->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script> 
    <!--ckeditor-->
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
    <!--Style icon-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
</head>
<body>
    <main class="container" >
      <div class="row mb-2 " >
        <div class="col-md-9" >
            <div class=" mb-2" >
              {% include 'core/menu.html' %}
            </div>  
            {% block content %}{% endblock %}
          </div>
          
          <div class="col-md-3">
              <div class="position-sticky" style="top: 0rem;">
                  <div class="p-4 mb-3 bg-dark bg-opacity-10 rounded" >
                      <h4 class="fst-italic">Categorias</h4>
                      <ol class="list-unstyled mb-0">
                        {% for item in categories %}
                          <li><a href={% url 'category' item.id %} class="text-decoration-none">
                          {{ item.name }}</a></li>
                        {% endfor %}
                      </ol>
                  </div>
                  <div class="p-4 mb-3 bg-dark bg-opacity-10 rounded">
                    <h4 class="fst-italic">Archivos</h4>
                    <ol class="list-unstyled mb-0">
                      {% for date in dates %}
                      <li><a href={% url 'date' date.month date.year %} class="text-decoration-none ">
                        {{ date | date:'M Y' }}</a></li>
                      {% endfor %}
                    </ol>
                  </div>
          
                  <div class="p-4 mb-3 bg-dark bg-opacity-10 rounded">
                    <h4 class="fst-italic">Nuestras Redes</h4>
                    <ol class="list-unstyled">
                      
                      {% for item in links %}
                      <li><a href={{ item.url }} class="text-decoration-none">
                        <i class="{{ item.icon }}"></i>  {{ item.name }}</a></li>
                      {% endfor %}
                                              
                    </ol>
                  </div>
                  <div class="p-4 mb-3 bg-dark bg-opacity-10 rounded">
                    <a href={% url 'abouts' %} class="text-decoration-none">
                    <h4 class="fst-italic">Acerca nuestro</h4>
                    </a>
                  </div>
              </div>
          </div>
      </div>
    </main>
    <footer class="blog-footer">
        <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
        <p>
          <a href="#">Back to top</a>
        </p>
    </footer>
</body>

</html>

core/templates/core/category.html
{% extends 'core/base.html' %}
{% block content %}
    {% if post_list %}
    <div class="alert alert-success" role="alert">
        Estos son todos los post de la categoria <strong>{{ category.name }}</strong>
    </div>
    {% endif %}
    {% for post in post_list %}  
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-300 position-relative">
        <div class="object-fit-cover col-auto d-none d-lg-block">
          <img src={{ post.image.url }} width="300" height="250"  class="img-fluid rounded-start " alt="...">          
        </div>
        
        <div class="col-6 p-2 d-flex flex-column position-static">
          <strong class="d-inline-block mb-1 mt-0 text-primary">{{ post.category }}</strong>
          <h3 class="mb-0">{{ post.title|truncatewords:'7' }}</h3>
          <div class="mb-1 text-muted">{{ post.created | date:'d b y'}}</div>
          <p class="card-text mb-auto">{{ post.excerpt|truncatewords:'30' }}</p>
          <a href={% url 'post' post.id %} class="stretched-link">Seguir leyendo</a>
        </div>
      </div>
      {% empty %}
      <div class="alert alert-danger" role="alert">
        <strong>No existen publicaciones en la categoria {{ category.name }}</strong>
      </div>
    {% endfor %}  
    <div class="justify-content-center">
      <a class="btn btn-outline-primary rounded-pill " href={% url 'home' %}>Volver al inicio</a>
    </div>
{% endblock %}

core/templates/core/date.html
{% extends 'core/base.html' %}
{% block content %}
    {% if post_list %}
    <div class="alert alert-success" role="alert">
        Estos son todos los post publicados en <strong>{{ date | date:'M Y'}}</strong>
    </div>
    {% else %}
    <div class="alert alert-danger" role="alert">
      No existe post publicados en <strong>{{ date | date:'M Y'}}</strong>
  </div>
    {% endif %}
    {% for post in post_list %}  
    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-300 position-relative">
      <div class="object-fit-cover col-auto d-none d-lg-block">
        <img src={{ post.image.url }} width="300" height="250"  class="img-fluid rounded-start " alt="...">          
      </div>
      
      <div class="col-6 p-2 d-flex flex-column position-static">
        <strong class="d-inline-block mb-1 mt-0 text-primary">{{ post.category }}</strong>
        <h3 class="mb-0">{{ post.title|truncatewords:'7' }}</h3>
        <div class="mb-1 text-muted">{{ post.created | date:'d b y'}}</div>
        <p class="card-text mb-auto">{{ post.excerpt|truncatewords:'30' }}</p>
        <a href={% url 'post' post.id %} class="stretched-link">Seguir leyendo</a>
      </div>
    </div>
    {% endfor %} 
{% endblock %}

core/templates/core/detail.html
{% extends 'core/base.html' %}
  {% block content %}
  <article class="blog-post">
    <div class="col-auto d-none d-lg-block">
        <img class="bd-placeholder-img" width="100%" height="auto" src={{ post.image.url }} preserveAspectRatio="xMidYMid slice" focusable="false">
    </div>
    <strong class="d-inline-block mb-2 mt-3 text-primary"><a href={% url 'category' post.category.id %}>{{ post.category }}</a></strong>
    <h2 class="blog-post-title mb-1">{{ post.title }}</h2>
    <p class="blog-post-meta">{{ post.created | date:'d b Y' }} por: <a href={% url 'author' post.author.id %}>{{ post.author }}</a></p>

    <p>{{ post.excerpt }}</p>
    <hr>
    <div class="container">
    <p class="blog-post">{{ post.content | safe }}</p>
    </div>
    <hr>
    <strong>Etiquetas</strong>
    {% for tag in post.tag.all %}
    <span class="badge text-bg-info">{{ tag | upper }}</span>
    {% endfor %}
    <br>
  </article> 
  <div class="text-center">
    <a class="btn btn-primary rounded-pill " href={% url 'home' %}>Volver al inicio</a>
    {% if post.author == request.user%}
      <a class="btn btn-danger rounded-pill float-end" href={% url 'delete' post.id %}>Eliminar</a>
      <a class="btn btn-warning rounded-pill float-end" href={% url 'update' post.id  %}>Editar</a>
    {% endif %}
  </div>
  
  {% endblock %}     

core/templates/core/home.html
{% extends 'core/base.html' %}

{% block content %}
  {% if post_list %}
    {% for post in post_list %}  
      {% if forloop.first and page_obj.number == 1 %}
          <div class="p-4 p-md-4 mb-4 rounded text-bg-dark">
            <div class="col-md-12 px-0">
            <h1 class="display-4 fst-italic text-secondary ">{{ post.title }}</h1>
            <p class="lead my-3">{{ post.excerpt }}</p>
            <p class="lead mb-0"><a href={% url 'post' post.id %} class="text-white fw-bold">Seguir leyendo...</a></p>
            </div>
          </div>
      {% else %}
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-300 position-relative">
          <div class="object-fit-cover col-auto d-none d-lg-block">
            <img src={{ post.image.url }} width="300" height="250"  class="img-fluid rounded-start " alt="...">          
          </div>
          
          <div class="col-6 p-2 d-flex flex-column position-static">
            <strong class="d-inline-block mb-1 mt-0 text-primary">{{ post.category }}</strong>
            <h3 class="mb-0">{{ post.title|truncatewords:'7' }}</h3>
            <div class="mb-1 text-muted">{{ post.created | date:'d b y'}}</div>
            <p class="card-text mb-auto">{{ post.excerpt|truncatewords:'30' }}</p>
            <a href={% url 'post' post.id %} class="stretched-link">Seguir leyendo</a>
          </div>
        </div>
      {% endif %}
    {% endfor %}  
  {% else %}
    <div class="alert alert-danger" role="alert">
      No hay post en el Blog 
    </div>
  {% endif %}
  
  <hr>
  <!-- barra paginacion -->
  <nav aria-label="...">
    <ul class="pagination justify-content-center">
      <li class="page-item {% if page_obj.number == 1 %}disabled{% endif %}">
        <a class="page-link" href="?page=1">Primera</a>
      </li>
      
      <li class="page-item {% if posts.number == 1 %}disabled{% endif %}">
        {% if page_obj.has_previous %}
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          {{ page_obj.previous_page_number }}
        </a>
        {% endif %}
      </li>
      
      <li class="page-item active" aria-current="page">
        <a class="page-link" >{{ page_obj.number }}</a>
      </li>

        {% if page_obj.has_next %}
        <li class="page-item ">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            {{ page_obj.next_page_number }}
          </a>
        </li>
        {% endif %}
      <li class="page-item {% if page_obj.number == page_obj.paginator.num_pages %}disabled{% endif %}">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Ultima</a>
      </li>
    </ul>
  </nav>
  <hr>  
  {% endblock %}

core/templates/core/menu.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-body-tertiary navbar-dark bg-dark">
  <div class="container mb-2">
    <a class="navbar-brand" href={% url 'home' %}>
      <img width="40" height="32" src={% static "core/img/blogger-icon.png" %}>
      Blog Semanal</a>
    {% if request.user.is_authenticated %}
    <div class="btn-group" >
      <div class="btn btn-light ">
        <a class="nav-link" href="{% url 'create' %}">Crear post</a>
      </div>
      <div class="btn btn-light ">
        <a class="nav-link" href="{% url 'author' user.id %}">Mis post</a>
      </div>
    </div> 
    {% endif %}
    {% if request.user.is_authenticated %}
    <div class="dropdown float-end">
      <button class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="bi bi-person-circle" style="font-size: 1.2em;"></i> {{ request.user.username }}
      </button>
      <ul class="dropdown-menu">
        <li><a class="dropdown-item" href={% url 'profile' user.id %}>Perfil</a></li>
        <li><a class="dropdown-item" href="{% url 'logout' %}?next={{request.path}}">Logout</a></li>
      </ul>
    </div>
    {% else %}
    <div class="dropdown float-end">
      <button class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="bi bi-person-circle" style="font-size: 1.2em;"></i> 
      </button>
      <ul class="dropdown-menu">
        <li><a class="dropdown-item" href={% url 'login' %}>Login</a></li>
        <li><a class="dropdown-item" href={% url 'register' %}>Registrarse</a></li>
      </ul>
    </div>
    {% endif %}
  </div>
</nav>

core/templates/core/post_confirm_delete.html
{% extends 'core/base.html' %}
{% block content %}
    <div class="mb-5 text-center">
        <form action="" method="post" >
            {% csrf_token %}
            <div class="card text-bg-danger mb-3 mx-auto" style="max-width: 18rem;">
                <div class="card-header">CONFIRMAR ACCION</div>
                <div class="card-body">
                  <h5 class="card-title">Eliminar post</h5>
                  <p class="card-text">Esta seguro que quierre eleminar el post titulado "<strong>{{ post.title }}</strong>"</p>
                  <div class="text-center">
                    <input class="btn btn-lg btn-light" type="submit" value="Si, Borrar el post">
                  </div>
                </div>
            </div>
            
        </form>
    </div>
{% endblock %}

core/templates/core/post_form.html
{% extends 'core/base.html' %}
{% block content %}
    <h2>Crear post</h2>
    <div class="mb-5">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="text-center">
                <input class="btn btn-lg btn-primary" type="submit" value="Crear post">
            </div>
        </form>
    </div>
{% endblock %}

core/templates/core/post_update_form.html
{% extends 'core/base.html' %}
{% block content %}
    <h2>Actualizar post</h2>
    {% if 'ok' in request.GET %}
    <div class="alert alert-success" role="alert">
        El post se actualizo correctamente
        <a href={% url 'post' post.id %} class="btn btn-sm btn-success">Ver post</a>
    </div>
    {% endif %}
    <div class="mb-5">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="text-center">
                <input class="btn btn-lg btn-warning rounded-pill" type="submit" value="Actualizar post">
            </div>
        </form>
    </div>
{% endblock %}